name: desafio_apirest
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  transparent_image: ^2.0.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  localstorage: ^4.0.0+1
  sqflite: ^2.0.3+1
  firebase_auth: ^4.1.2
  google_sign_in: ^5.4.2
  firebase_core: ^2.2.0
  cloud_firestore: ^4.0.5
  flutter_native_splash: ^2.2.9
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mocktail: ^0.3.0

flutter_icons:
  image_path: "assets/images/sacolas-de-compras.png"
  ios: true
  remove_alfa_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FF6347"
  adaptive_icon_foreground: "assets/images/sacolas-de-compras.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
